<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Application extends Model
{
    use HasFactory;
    protected $fillable = [
        'first_name',
        'middle_name',
        'last_name',
        'interested_country',
        'dob',
        'mobile_no',
        'whatsapp_no',
        'copy_mobile_no',
        'gender',
        'marital_status',
        'spouse_name',
        'citizenship_no',
        'issue_district',
        'issue_date',
        'email_address',
        'state',
        'district',
        'city',
        'ward_no',
        'village_tole_chowk',
        'father_name',
        'father_contact',
        'mother_name',
        'mother_contact',
        'other_relative_name',
        'other_relative_contact',
        'relative_relation',
        'passport_no',
        'passport_issue_date',
        'passport_expire_date',
        'passport_upload',
        'police_report_upload',
        'lang_nepali',
        'lang_english',
        'lang_hindi',
        'lang_other',
        'other_language',
        'education_level',
        'edu_level_doc_upload',
        'license_no',
        'license_category',
        'license_issue_date',
        'license_expire_date',
        'license_upload',
        'worked_in_nepal',
        'nepal_company',
        'nepal_company_address',
        'nepal_post',
        'nepal_working_period',
        'nepal_work_cert_upload',
        'been_abroad',
        'abroad_country',
        'abroad_company',
        'abroad_post',
        'abroad_working_period',
        'abroad_work_cert_upload',
        'applied_before',
        'applied_country',
        'agent_manpower',
        'applied_when',
        'hear_about_us',
        'other_source',
    ];
}
